### ISSUE TITLE
lifx-z: Has this been tested

### ISSUE THREAD

**Issue by ghost** [pdf/golifx#10]
have you tested against the new z ?
https://www.lifx.com/products/lifx-z

I want to buy about 10 of these, but wanted to check if you have tried this actual product yet.

**Comment by pdf** [comment]
I don't own any, and there's currently no multi-zone support in this lib, so you won't be able to do anything fancy with them.

**Comment by ghost** [comment]
ok thanks.

might have to write some code for multizone.
