### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by anthonycastelli** [pdf/golifx#11]
There appears to be a pretty big memory leak when using this library in the hklifxd HomeKit bridge. After spending some time looking into this, it appears that golifx is the culprit. I'm not a go developer so it's a bit out of my league to investigate the leak.

**Comment by pdf** [comment]
I'm sorry, I'm aware of outstanding issues with this lib, and I have a pretty good idea of the cause of your problem, but I have not allocated any time to fixing it for far too long.  I'll try and find some time soon to sort this out properly.

**Comment by anthonycastelli** [comment]
No worries. Thanks for the response! 😊

**Comment by bland328** [comment]
Thanks, @pdf...I'm just speaking up as another person who's impacted by this one. Thanks for all the great work you've done!

**Comment by anthonycastelli** [comment]
@pdf Just wanted to check in and see if you've had any time to take a look at this leak?

**Comment by pdf** [comment]
I've made some changes, but it's complicated and time-consuming, so I can't be sure if your problems are solved.  Please follow brutella/hklifx#22 for further updates.
