### ISSUE TITLE
Powerless and wireless light switches

### ISSUE THREAD

**Issue by ghost** [pdf/golifx#12]
Am planning to replace all wall light switches with radio based ones.

Do you know any ? 

This is so that the lights can be controlled by and app as well as a wall light switch.

It can also be powered because it's a renovation so I could just power the radio light switch via the 230 volts running behind each switch

**Comment by pdf** [comment]
I don't have any experience with them personally, you'll probably get more eyes on this question in the [community forums](https://community.lifx.com/).

**Comment by ghost** [comment]
I found on :) so for there...

Sonoff

It's amazing and you can do OTA upgrades and tasmoto firmware supports mqtt.

This is really amazing because it 6 euro per board

**Comment by ghost** [comment]
Here you go

Lights
Sonoff hardware light switches
Mqtt tasmoto code: https://github.com/arendst/Sonoff-Tasmota
