### ISSUE TITLE
Crash on concurrent map access

### ISSUE THREAD

**Issue by brutella** [pdf/golifx#4]
Occasionally I get the following crash

```
fatal error: concurrent map read and map write

goroutine 25054 [running]:
runtime.throw(0x616060, 0x21)
    /usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:530 +0x90 fp=0xc820218be8 sp=0xc820218bd0
runtime.mapaccess2(0x4b1e00, 0xc8201470e0, 0xc820218c67, 0xc82000a2a0, 0x2)
    /usr/local/Cellar/go/1.6/libexec/src/runtime/hashmap.go:343 +0x5a fp=0xc820218c30 sp=0xc820218be8
github.com/pdf/golifx/protocol/v2/device.(*Device).handler(0xc8203b4c40)
    /Users/mah/Source/Code/Go/src/github.com/pdf/golifx/protocol/v2/device/device.go:634 +0x4c1 fp=0xc820218fa8 sp=0xc820218c30
runtime.goexit()
    /usr/local/Cellar/go/1.6/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820218fb0 sp=0xc820218fa8
created by github.com/pdf/golifx/protocol/v2/device.New
    /Users/mah/Source/Code/Go/src/github.com/pdf/golifx/protocol/v2/device/device.go:689 +0x165
```

**Comment by pdf** [comment]
I was aware this was likely an issue - to solve it I had to change one of the undocumented structs, so if you're using `github.com/pdf/golifx/protocol/v2/device.Light` as opposed to `common.Light` anywhere, you should be aware that the embedded `Device` is now a pointer.

As a bonus, this prompted me to review a bunch of the other code, and remove races there, though they weren't map accesses, so they would not have been producing crashes on Go 1.6.  There may be a couple left, I'll try and do some more review in the near future.

Should also probably note that while I believe this should be in pretty good shape, I've not done extensive testing yet, so you might want to put it through its paces before you push anything out to users.
